import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Download } from 'lucide-react';
import { isApiError } from '@/lib/api';
import { PermissionGuard } from '@/features/auth/PermissionGuard';
import { formatDate } from '@/lib/utils/format';
import { ContentSection, PageHeader } from '@/shared/layout/page';
import { Badge, Button, Card, CardBody, QueryBoundary, Skeleton, toast } from '@/shared/ui';
import { useExportReport, useReport } from '../hooks/useReports';
import { reportCategoryTone } from '../category';
import { REPORT_CATEGORY_LABEL, type ReportResult } from '../types';

/**
 * Report detail (§ reporting).
 *
 * Renders the metrics and table exactly as the backend computed them — every
 * value is display-ready and shown verbatim; the frontend never aggregates or
 * derives a figure. Export is gated on `reports.export`; the backend prepares
 * the file, which the client never generates.
 */
export function ReportDetailPage() {
  const { reportId = '' } = useParams();
  const query = useReport(reportId);

  return (
    <>
      <Link
        to="/management/reports"
        className="mb-3 inline-flex items-center gap-1 text-body-sm text-[var(--text-muted)] hover:text-[var(--text)]"
      >
        <ArrowLeft className="size-4" aria-hidden="true" />
        Back to reports
      </Link>

      <QueryBoundary
        isPending={query.isPending}
        isError={query.isError}
        error={query.error}
        onRetry={() => void query.refetch()}
        loadingFallback={
          <Card>
            <CardBody className="flex flex-col gap-4">
              <Skeleton className="h-7 w-48" />
              <Skeleton className="h-40 w-full" />
            </CardBody>
          </Card>
        }
      >
        {query.data && <ReportDetailView report={query.data} />}
      </QueryBoundary>
    </>
  );
}

function ReportDetailView({ report }: { report: ReportResult }) {
  const exportReport = useExportReport(report.id);

  async function runExport() {
    try {
      const result = await exportReport.mutateAsync();
      toast.success('Export requested', result.message);
    } catch (error) {
      const message = isApiError(error) ? error.message : 'The export could not be requested.';
      toast.error('Export failed', message);
    }
  }

  return (
    <>
      <PageHeader
        title={report.name}
        description={report.summary}
        meta={<Badge tone={reportCategoryTone(report.category)}>{REPORT_CATEGORY_LABEL[report.category] ?? report.category}</Badge>}
        actions={
          <PermissionGuard permission="reports.export">
            <Button variant="secondary" loading={exportReport.isPending} onClick={() => void runExport()}>
              <Download className="size-4" aria-hidden="true" />
              Export
            </Button>
          </PermissionGuard>
        }
      />

      {report.generatedAt && (
        <p className="mb-4 text-body-sm text-[var(--text-subtle)]">Generated by the backend on {formatDate(report.generatedAt)}.</p>
      )}

      {report.metrics.length > 0 && (
        <div className="mb-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
          {report.metrics.map((metric) => (
            <Card key={metric.label}>
              <CardBody className="flex flex-col gap-1">
                <span className="text-caption font-semibold tracking-wide text-[var(--text-muted)] uppercase">{metric.label}</span>
                {/* Backend-computed value — displayed verbatim. */}
                <span className="text-metric font-semibold tabular-nums text-[var(--text)]">{metric.value}</span>
              </CardBody>
            </Card>
          ))}
        </div>
      )}

      {report.table && (
        <ContentSection title="Breakdown">
          <Card className="overflow-x-auto">
            <table className="w-full text-body">
              <caption className="sr-only">{report.name} breakdown</caption>
              <thead>
                <tr className="border-b border-[var(--border)] text-caption text-[var(--text-muted)] uppercase">
                  {report.table.columns.map((column, index) => (
                    <th key={column} scope="col" className={`px-4 py-2.5 font-semibold tracking-wide ${index === 0 ? 'text-left' : 'text-right'}`}>
                      {column}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {report.table.rows.map((row, rowIndex) => (
                  <tr key={rowIndex} className="border-b border-[var(--border)] last:border-0">
                    {row.map((cell, cellIndex) => (
                      <td key={cellIndex} className={`px-4 py-2.5 text-[var(--text)] ${cellIndex === 0 ? 'text-left font-medium' : 'text-right tabular-nums'}`}>
                        {cell}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>
        </ContentSection>
      )}
    </>
  );
}
